# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- releases/*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:  
  - job: Publish_Dotnet
    displayName: Build
    
    steps:
    - task: CmdLine@2
      inputs:
        script: 'ng build'
        workingDirectory: '$(Build.SourcesDirectory)/myBlogSPA/'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        zipAfterPublish: false
        modifyOutputPath: false
  
  
  - job: Build_Docker
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/myBlog.API/Dockerfile'
        tags: |
          $(tag)