# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- releases/*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  
pool: Default
  

stages:
- stage: Build
  jobs:  
  - job: Build_Angular_and_Dotnet
    
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '8.3'
      displayName: 'Install Node.js'

    - script: |
        cd myBlogSPA
        npm install -g @angular/cli
        npm install
        ng build 
      displayName: 'npm install and build'
    
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          cp ~/*.json ./myBlog.API

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: 'myBlog.API/myBlog.API.csproj'
        zipAfterPublish: false
        modifyOutputPath: false

  - job: Build_Docker
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/myBlog.API/Dockerfile'
        tags: |
          $(tag)