version: '3'
services:
  mysql:
    container_name: test_mysql
    image: mysql:8.0
    volumes:
      - ${VOLUME_PATH}/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    networks:
      app_net:
        ipv4_address: ${MYSQLIP}
    security_opt:
      - seccomp:unconfined
    
  mongo:
    container_name: test_mongo
    image: mongo
    volumes:
     - ${VOLUME_PATH}/mongo_data:/data/db
    restart: always
    networks:
      app_net:
        ipv4_address: ${MONGOIP}

  dotnet:
    container_name: test_myBlog
    depends_on:
     - mysql
     - mongo
    image: qidongs/myblog
    ports:
      - "5003:5003"
      - "80:80"
      - "443:443"
    networks:
      app_net:
        ipv4_address: ${DOTNETIP}
    restart: always
    
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "${SUBNET}"