version: '3'
services:
   mysql:
     image: qidongs/mysql-server
     volumes:
       - mysql_data:/var/lib/mysql
     restart: always
    
    mongo:
      image: mongo
      volumes:
       - mongo_data:/data/db
      restart: always

   dotnet:
     depends_on:
       - mysql
       - mongo
     image: qidongs/myblog
     volumes:
        - myblog:/APP/
     ports:
       - "80:80"
       - "443:443"
     restart: always

